import React from "react";
import { Raleway } from "next/font/google";
import StyledComponentsRegistry from "@/providers/AntdProvider";
import TanstackProvider from "@/providers/TanstackProvider";
import { AuthContextProvider } from "@/providers/AuthProvider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "@/app/globals.css";
import "@/scss/main.scss";

const inter = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <AuthContextProvider>
            <StyledComponentsRegistry>
              <Header />
              <main>{children}</main>
              <Footer />
            </StyledComponentsRegistry>
          </AuthContextProvider>
        </TanstackProvider>
      </body>
    </html>
  );
};
export default RootLayout;
