import React from "react";
import { Raleway } from "next/font/google";
import { dir } from "i18next";
import StyledComponentsRegistry from "@/providers/AntdProvider";
import TanstackProvider from "@/providers/TanstackProvider";
import { AuthContextProvider } from "@/providers/AuthProvider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "@/app/globals.css";
import "@/scss/main.scss";
import { languages } from "@/i18n/settings";

const inter = Raleway({ subsets: ["latin"] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children, params: { lng } }) => {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <TanstackProvider>
          <AuthContextProvider>
            <StyledComponentsRegistry>
              <Header />
              <main>{children}</main>
              <Footer />
            </StyledComponentsRegistry>
          </AuthContextProvider>
        </TanstackProvider>
      </body>
    </html>
  );
};
export default RootLayout;
